"""Refactor regression tests — preambles moved to hermes-blind in v0.1.3.

These tests assert that:
  1. The deprecation shim at ``hermes_rubric.preambles`` re-exports the
     same symbols hermes-rubric v0.1.2 shipped.
  2. The CLI flags ``--scope-class`` and ``--intent-debias`` produce
     byte-identical synthesize-stage prompts as the pre-refactor
     hermes-rubric v0.1.2 codebase.
"""
from __future__ import annotations

import json
from unittest.mock import patch

import pytest


# ---- (1) shim re-exports ----

def test_shim_reexports_intent_debias_preamble():
    from hermes_blind.preambles import INTENT_DEBIAS_PREAMBLE as upstream
    from hermes_rubric.preambles import INTENT_DEBIAS_PREAMBLE as shim
    assert shim is upstream


def test_shim_reexports_scope_preambles():
    from hermes_blind.preambles import SCOPE_PREAMBLES as upstream
    from hermes_rubric.preambles import SCOPE_PREAMBLES as shim
    assert shim is upstream


def test_shim_reexports_scope_choices():
    from hermes_blind.preambles import SCOPE_CHOICES as upstream
    from hermes_rubric.preambles import SCOPE_CHOICES as shim
    assert shim == upstream
    assert set(shim) == {"gate-plan", "sweep-plan", "results-bundle"}


def test_shim_reexports_compose_intent():
    from hermes_blind.preambles import compose_intent as upstream
    from hermes_rubric.preambles import compose_intent as shim
    assert shim is upstream


# ---- (2) frozen-prompt byte identity ----

# This is the pre-refactor expected synthesize prompt for a fixed
# (intent, context, target_type, scope_class, intent_debias) tuple. It was
# generated by running synthesize() against the v0.1.2 code path; if the
# refactor changes the prompt by a single byte, this test will fail.
_FROZEN_INTENT = "evaluate whether the gate plan is sound and ready to ship"
_FROZEN_CONTEXT = "fixed-context-summary-for-byte-identity-check"
_FROZEN_TARGET_TYPE = "gate-plan-document"


def _build_expected_prompt(scope_class: str | None, debias: bool) -> str:
    """Reconstruct the expected synthesize prompt the way the pre-refactor
    code path did: compose intent first, then format the synth template.

    We import the (now-moved) helpers from hermes_blind to *generate* the
    expected prompt rather than hard-coding it — that ensures we are
    asserting "synthesize() builds a prompt by composing then formatting,"
    not just memorizing the bytes. Any byte-level drift in either the
    preambles or the template will still fail the test below.
    """
    from hermes_blind import wrap_intent_for_rubric
    from hermes_rubric.synthesize import _SYNTH_PROMPT_TEMPLATE

    composed = wrap_intent_for_rubric(
        _FROZEN_INTENT, scope_class=scope_class, debias=debias
    )
    return _SYNTH_PROMPT_TEMPLATE.format(
        intent=composed,
        target_type=_FROZEN_TARGET_TYPE,
        context_summary=_FROZEN_CONTEXT[:4000],
    )


def _rubric():
    return {
        "rubric_intent": "test",
        "target_type": "x",
        "dimensions": [
            {"id": f"dim_{i}", "name": f"D{i}", "description": "d",
             "evidence_instructions": "e", "weight": 1, "hedge": False}
            for i in range(1, 4)
        ],
    }


@pytest.mark.parametrize(
    "scope_class,debias",
    [
        (None, False),
        (None, True),
        ("gate-plan", False),
        ("results-bundle", False),
        ("sweep-plan", True),
        ("results-bundle", True),
    ],
)
def test_synthesize_produces_byte_identical_prompt(scope_class, debias):
    """The synthesize stage must produce the exact same prompt bytes as
    the pre-refactor code path for every (scope_class, debias) combo.
    """
    from hermes_rubric import synthesize as synth_mod

    captured = {}

    def fake_call(prompt, backend=None, max_tokens=2048):
        captured["prompt"] = prompt
        return json.dumps(_rubric())

    with patch.object(synth_mod.backends, "call", side_effect=fake_call):
        synth_mod.synthesize(
            intent=_FROZEN_INTENT,
            context_summary=_FROZEN_CONTEXT,
            target_type=_FROZEN_TARGET_TYPE,
            backend="claude-cli",
            scope_class=scope_class,
            intent_debias=debias,
        )

    expected = _build_expected_prompt(scope_class, debias)
    assert captured["prompt"] == expected, (
        f"Prompt drift detected for scope_class={scope_class!r} debias={debias}.\n"
        f"Expected first 200 chars: {expected[:200]!r}\n"
        f"Got first 200 chars:      {captured['prompt'][:200]!r}"
    )


# ---- (3) CLI flag surface unchanged ----

def test_cli_scope_class_choices_match_hermes_blind():
    """The argparse choices must equal hermes_blind's SCOPE_CHOICES."""
    import argparse
    from unittest.mock import patch as _patch

    from hermes_blind import SCOPE_CHOICES
    from hermes_rubric import cli as cli_mod

    # Build the same parser cli.py builds, by intercepting parse_args.
    captured_parser: dict[str, argparse.ArgumentParser] = {}

    real_parse_args = argparse.ArgumentParser.parse_args

    def grab_parser(self, *a, **kw):
        captured_parser["p"] = self
        # Stop the CLI before it tries to actually run.
        raise SystemExit(0)

    with _patch.object(argparse.ArgumentParser, "parse_args", grab_parser):
        with _patch("sys.argv", ["hermes-rubric", "--intent", "x",
                                 "--context", "/dev/null", "--target", "/dev/null"]):
            with pytest.raises(SystemExit):
                cli_mod.main()

    parser = captured_parser["p"]
    # Find the --scope-class action.
    scope_action = next(
        a for a in parser._actions if "--scope-class" in (a.option_strings or [])
    )
    assert tuple(scope_action.choices) == SCOPE_CHOICES

    # Sanity: real_parse_args is still callable (we didn't break it).
    assert callable(real_parse_args)
